# JWT Configuration
jwt.secret=Y1c0c1NlY3VyZVNlY3JldEtleUZvcldhcm1VcENvbGxlY3Rpb25BcHA=
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# Security Configuration
security.require-ssl=true
security.enable-csrf=false
security.session-creation=stateless

jdbc.driverClassName=com.mysql.cj.jdbc.Driver

# Connexion base de donnee GEDI
# jdbc.url = jdbc:mysql://localhost:3306/gedidb_2025?useUnicode=true&characterEncoding=latin1&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull

jdbc.url = jdbc:mysql://localhost:3306/enmgdb21-2020?useUnicode=true&characterEncoding=latin1&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
jdbc.username = root
jdbc.password = 

hibernate.dialect = org.hibernate.dialect.MySQLDialect
hibernate.show_sql = true
hibernate.format_sql = false

jdbc.ip=localhost
jdbc.port=3306
jdbc.dbname = gedidb_2025
